FROM aschzero/hera:latest
LABEL maintainer="Amin Shah Gilani <pars@gilani.me>" \
      description="PARS managed Echolink gateway run on Raspberry Pi"

COPY scripts/run.sh run.sh

ENTRYPOINT ["/run.sh"]
