version: '2'
services:
  svxlink:
    build: ./svxlink
    devices:
      - "/dev/snd:/dev/snd"
    env_file:
      - ./svxlink-vars.env
    expose:
      - "5198"
      - "5199"
      - "5200"
  web:
    image: nginxdemos/hello
    expose:
      - "80"
