version: '2'

services:
  svxlink:
    build: ./svxlink
    devices:
      - "/dev/snd:/dev/snd"
    env_file:
      - ./svxlink-vars.env
    expose:
      - "5198"
      - "5199"
      - "5200"
    networks:
      - hera

  nginx:
    image: nginx:latest
    networks:
      - hera
    labels:
      hera.hostname: mysite.com
      hera.port: 80

  hera:
    build: ./tunnel
    labels:
      io.balena.features.balena-socket: '1'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - hera
networks:
  hera:
