version: '2'
services:
  svxlink:
    privileged: true
    build: ./svxlink
    devices:
      - "/dev/snd:/dev/snd"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    ports:
      - "5198:5198/udp"
      - "5199:5199/udp"
      - "5200"
    networks:
      - host
