version: '2'
services:
  svxlink:
    build: ./svxlink
    devices:
      - "/dev/snd:/dev/snd"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/-32:/dev/-32"
    expose:
      - "5198"
      - "5199"
      - "5200"
  web:
    image: nginxdemos/hello
    expose:
      - "80"
